### PR TITLE
Added support for point data, which also involved handling string enc…

### PR DESCRIPTION
**Pull request by loosepolygon**
…oding properly.

### CODE REVIEW

**Comment by Wulf2k** [comment]
Looks interesting, but it'll take me some time to go through the changes, understand them, and test.

Thanks for the contribution.

**Comment by loosepolygon** [comment]
Hey, sorry for not communicating. I've been busy coding, ha.

This fork has turned into a huge pitchfork. All I wanted to do was move the new game starting spawn and play around with adding enemies, and I accidentally made it completely usable. Oops.

I'm wondering about what to do with all this. Should I split the fork into my own project, or will you accept the pull request (or add me as a contributor?)

**Comment by Wulf2k** [comment]
I've been away all weekend in "the nature", but I've been impressed at the gist of the improvements I've been getting notifications for.

I'll make some time tomorrow to go over the changes, and if i like what i see I'll probably go ahead and make you a contributor.

Assuming you wanna keep making improvements beyond what youve

**Comment by Wulf2k** [comment]
...damn phone.  Ignore that close.

**Comment by Wulf2k** [comment]
I'm not gonna be at a machine capable of running DS for a while, but have you been testing as you go?

I'm tempted to just merge this as-is and sort out the testing later, it looks good conceptually and you seem pretty on-the-ball with things.

**Comment by loosepolygon** [comment]
I've been kind of lax as far as testing goes. There's still something broken right now that I want to fix today. But I've been planning on going through every map and testing it out after adding some random objects. Also, I have a mod idea to follow through on, and it's pretty important that it all works correctly.

**Comment by Wulf2k** [comment]
Is the "fixed a crash" one the "something broken" that you mentioned?

Is it pretty much ready to go as far as you're aware?  I've been holding off starting testing until then.

**Comment by loosepolygon** [comment]
The broken part was the point/part pointers (I'm bad at naming things) in the events section. They weren't being updated when points/parts were added or deleted. So hopefully *now* it's in a state where it's possible to edit anything and produce a valid file. It's still not completely user friendly, though user friendliness isn't really in the scope of this project right now, if you know what I mean. It's just a raw view of the file.

Real life stuff kind of ended my productivity streak, otherwise I would have done a lot of testing. It's certainly ready, to answer your question.

**Pull request merged**
